var kyodai={mapX:19,mapY:11,mapLength:14};kyodai.area="public";kyodai.imageshost="http://dw-kyodai.googlecode.com/svn/trunk/images/";kyodai.scene="tooth";kyodai.totalscores=0;kyodai.record=0;kyodai.level=0;kyodai.levelscore=[0,1E4,3E4,1E5,2E5,35E4,5E5,1E6];kyodai.getCachedImage=function(a){return kyodai.area=="public"?_IG_GetImageUrl(kyodai.imageshost+a):"images/"+a};kyodai.getTotalscores=function(){kyodai.totalscores=kyodai.prefs.getInt("totalscores");$("#myscore").html(kyodai.totalscores)};
kyodai.getRecord=function(){kyodai.record=kyodai.prefs.getInt("record");$("#myrecord").html(kyodai.record)};kyodai.getLevel=function(){kyodai.level=kyodai.prefs.getInt("level");$("#levelimg").attr("src",kyodai.getCachedImage("level"+kyodai.level+".png"));$("#mylevel").html("Level "+kyodai.level)};
kyodai.preload=function(){$("#kyodai_game").attr("src",kyodai.getCachedImage("game1.jpg"));$("#kyodai_choose").attr("src",kyodai.getCachedImage("choose.png"));$("#kyodai_hover").attr("src",kyodai.getCachedImage("choose.png"));$("#kyodai_count img").attr("src",kyodai.getCachedImage("count.png"));$("#kyodai_ppt img").attr("src",kyodai.getCachedImage("notool.png"));$("#levelimg").attr("src",kyodai.getCachedImage("level0.png"));if(kyodai.area=="public"){kyodai.prefs=new _IG_Prefs;kyodai.getTotalscores();
kyodai.getRecord();kyodai.getLevel()}var a=[];for(i=0;i<42;i++){a.push('<img class="preload" src="'+kyodai.getCachedImage(kyodai.scene+"/"+i+".png")+'">');a.push('<img class="preload" src="'+kyodai.getCachedImage("linex.png")+'">');a.push('<img class="preload" src="'+kyodai.getCachedImage("liney.png")+'">')}for(i=1;i<6;i++){a.push('<img class="preload" src="'+kyodai.getCachedImage("tool"+i+".png")+'">');a.push('<img class="preload" src="'+kyodai.getCachedImage("tool_num_"+i+".png")+'">')}a.push('<img class="preload" src="'+
kyodai.getCachedImage("start_btn_hover.png")+'">');$("#kyodai_preload").html(a.join(""))};
kyodai.start=function(){$("#kyodai_scores").html("");$("#kyodai_combo").html("");$("#kyodai_combo").css("color","#CCC");$("#kyodai_board").css("color","#CCC");$("#kyodai_center").css("display","none");kyodai.sound(1);kyodai.cancel();kyodai.pptnum={1:3,2:3};$("#kyodai_ppt").html('<img id=kyodai_ppt_1 src ="'+kyodai.getCachedImage("tool1.png")+'"><img id=kyodai_ppt_2 src ="'+kyodai.getCachedImage("tool2.png")+'">');$("#kyodai_ppt_num").html('<img id=kyodai_ppt_1_num src ="'+kyodai.getCachedImage("tool_num_3.png")+
'"><img id=kyodai_ppt_2_num src ="'+kyodai.getCachedImage("tool_num_3.png")+'">');$("#kyodai_ppt_1_num").click(function(){kyodai.use(1)});$("#kyodai_ppt_2_num").click(function(){kyodai.use(2)});document.onkeydown=function(){event.keyCode==49&&kyodai.pptnum[1]&&kyodai.use(1);event.keyCode==50&&kyodai.pptnum[2]&&kyodai.use(2)};kyodai.scores=0;kyodai.combo=0;kyodai.speed=0;kyodai.highestcombo=0;kyodai.counts=0;kyodai.loadmap(Math.floor(Math.random()*kyodai.mapLength))};
kyodai.loadmap=function(a){kyodai.block={};kyodai.shape=[];a=["1-------111-------1\n-1-111111-111111-1-\n--111-111-111-111--\n--11--111-111--11--\n--11-111---111-11--\n-------------------\n--11-111---111-11--\n--11--111-111--11--\n--111-111-111-111--\n-1-111111-111111-1-\n1-------111-------1","-1-1-1-1-1-1-1-1-1-\n1-1-1-1-1-1-1-1-1-1\n-1-1-1-1-1-1-1-1-1-\n1-1-1-1-1-1-1-1-1-1\n-1-1-1-1-1-1-1-1-1-\n1-1-1-1-1-1-1-1-1-1\n-1-1-1-1-1-1-1-1-1-\n1-1-1-1-1-1-1-1-1-1\n-1-1-1-1-1-1-1-1-1-\n1-1-1-1-1-1-1-1-1-1\n-1-1-1-1-1-1-1-1-1-",
"1-------111-------1\n-1-111111-111111-1-\n--111-111-111-111--\n--11--111-111--11--\n--11-111---111-11--\n-------------------\n--11-111---111-11--\n--11--111-111--11--\n--111-111-111-111--\n-1-111111-111111-1-\n1-------111-------1","-------------------\n----11111-11111----\n---111111-111111---\n--111111---111111--\n-111111-----111111-\n-------------------\n-111111-----111111-\n--111111---111111--\n---111111-111111---\n----11111-11111----\n-------------------","---1-----1-----1---\n--111---111---111--\n-11111-11111-11111-\n--111---111---111--\n---1-----1-----1---\n-------------------\n-11-11-11-11-11-11-\n-1---1-1---1-1---1-\n---1-----1-----1---\n-1---1-1---1-1---1-\n-11-11-11-11-11-11-",
"11--1--11111--1--11\n1--1--1-----1--1--1\n1-1--1--111--1--1-1\n1-1-1--1---1--1-1-1\n1-1-1-1-----1-1-1-1\n1-1-1-1-----1-1-1-1\n1-1-1-1-----1-1-1-1\n1-1-1--1---1--1-1-1\n1-1--1--111--1--1-1\n1--1--1-----1--1--1\n11--1--11111--1--11","-1----111-111----1-\n-11---111-111---11-\n--11---11111---11--\n---11---111---11---\n1---11---1---11---1\n11---11-----11---11\n1---11---1---11---1\n---11---111---11---\n--11---11111---11--\n-11---111-111---11-\n-1----111-111----1-","11111---------11111\n111111-------111111\n-111111-----111111-\n--11111-----11111--\n-------------------\n-------------------\n-111-1-1-1-1-1-111-\n---1-1-1-1-1-1-1---\n---11-1-1-1-1-11---\n----11111111111----\n---------1---------",
"1111111111111111111\n1-----------------1\n1-111111111111111-1\n1-1-------------1-1\n1-1-1111111111--1-1\n1-1-1-----------1-1\n1-1-1111111111111-1\n1-1---------------1\n1-11111111111111111\n1------------------\n1111111111111111111","-------------------\n---1--1111111--1---\n--11-1111-1111-11--\n-111-111---111-111-\n-111-11-----11-111-\n-1-1-11-----11-1-1-\n-111-11-----11-111-\n-111-111---111-111-\n--11-1111-1111-11--\n---1--1111111--1---\n-------------------","---111111111111111-\n--11111111111111111\n--11---------------\n--11--1111111111---\n--11--11111111111--\n--11-----------11--\n--11111111111--11--\n---1111111111--11--\n---------------11--\n11111111111111111--\n-111111111111111---",
"---1111111111111111\n-1-11----1---1--1-1\n1--11----1---1--1-1\n1-111----1---1--1-1\n11111----1---1--1-1\n-111111111111111111\n11111----1---1--1-1\n1-111----1---1--1-1\n1--11----1---1--1-1\n-1-11----1---1--1-1\n---1111111111111111","---11-------1111---\n--1111-----111111--\n-111111---11111111-\n11-11-11---111111--\n---11-------1111---\n---11--------11----\n--1111----11111111-\n-111111---11111111-\n11111111-----11----\n-111111------11----\n--1111-------11----","1-------111-------1\n-1-111111-111111-1-\n--111-111-111-111--\n--11--111-111--11--\n--11-111---111-11--\n-------------------\n--11-111---111-11--\n--11--111-111--11--\n--111-111-111-111--\n-1-111111-111111-1-\n1-------111-------1"][a].split("\n");
blen=a.length;bxlen=a[0].length;for(var b=0;b<blen;b++){bx=a[b];for(var c=0;c<bxlen;c++)bx.charAt(c)=="1"&&kyodai.shape.push({x:c,y:b})}a=[];b=kyodai.random([1,2,3,4,5,6,7,8]);c=2;for(var d=kyodai.shape.length,e=0;e<8;e++){if(a.length==28)c=1;if(a.length==30)break;for(var f=Math.floor(Math.random()*c)*2+2;f>0;f--)a.push(b[e])}for(c=9;c<42;c++){if(d-a.length<3){if(d!=a.length){a.push(c);a.push(c)}break}a.push(c);a.push(c);a.push(c);a.push(c)}$("#kyodai_remain").html("Remain : "+d);kyodai.remain=d;
kyodai.setting(a);kyodai.count()};
kyodai.setting=function(a){var b=[];kyodai.shape=kyodai.random(kyodai.shape);for(i=0;i<kyodai.shape.length;i++){var c=a[i];x=kyodai.shape[i].x;y=kyodai.shape[i].y;(kyodai.block[x+","+y]=c)&&b.push("<img id=Item_"+x+"_"+y+' class ="block_item" src="'+kyodai.getCachedImage(kyodai.scene+"/"+c+".png")+'" style="z-index:'+(100-x+y)+";position:absolute;left:"+x*35+"px;top:"+y*35+'px">')}$("#kyodai_items").html(b.join(""));$(".block_item").click(function(){kyodai.click($(this).position().left,$(this).position().top)});
$(".block_item").hover(function(){$("#kyodai_hover").css("left",$(this).position().left+"px");$("#kyodai_hover").css("top",$(this).position().top+"px")},function(){$("#kyodai_hover").css("left","-2000px")})};
kyodai.click=function(a,b){a=Math.ceil(a/35);b=Math.ceil(b/35);if(kyodai.block[a+","+b]){kyodai.sound(2);if(kyodai.point){var c=kyodai.point.x,d=kyodai.point.y,e=c+","+d,f=a+","+b;if(e==f){kyodai.cancel();kyodai.combo=0;kyodai.updatecombo()}else{var j=kyodai.block[e],k=kyodai.block[f];if(j!=k){kyodai.choose(a,b);kyodai.combo=0;kyodai.updatecombo()}else{kyodai.cancel();kyodai.block[e]=0;kyodai.block[f]=0;var l=kyodai.find(c,d,a,b);if(l){$("#kyodai_lines").html(l.join(""));$("#kyodai_lines img").hide();
$("#kyodai_lines img").fadeIn("fast");$("#kyodai_lines img").fadeOut("fast");kyodai.del(c,d,a,b)}else{kyodai.block[e]=j;kyodai.block[f]=k;kyodai.combo=0;kyodai.updatecombo()}}}}else kyodai.choose(a,b)}};kyodai.choose=function(a,b){$("#kyodai_cuechoose").html("");kyodai.point={x:a,y:b};$("#kyodai_choose").css("left",a*35+"px");$("#kyodai_choose").css("top",b*35+"px")};kyodai.cancel=function(){$("#kyodai_cuechoose").html("");kyodai.point=false;$("#kyodai_choose").css("left","-2000px")};
kyodai.del=function(a,b,c,d){kyodai.sound(3);kyodai.remain-=2;$("#kyodai_remain").html("Remain : "+kyodai.remain);$("#Item_"+a+"_"+b).fadeOut("fast");$("#Item_"+c+"_"+d).fadeOut("fast");if(kyodai.counts>295){if(kyodai.speed<10)kyodai.speed+=1;kyodai.speedscore=5*kyodai.speed;kyodai.scores+=kyodai.speedscore;kyodai.updatespeed();kyodai.updateupdate(kyodai.speedscore);kyodai.updatescore()}else kyodai.speed=0;if(kyodai.counts>210){kyodai.combo+=1;if(kyodai.combo>kyodai.highestcombo)kyodai.highestcombo=
kyodai.combo;kyodai.updatecombo();kyodai.scores+=10;kyodai.updateupdate(10);kyodai.updatescore()}else{kyodai.combo=0;kyodai.updatecombo()}kyodai.count();kyodai.remain||setTimeout("kyodai.over('win')",500)};
kyodai.updatespeed=function(){switch(kyodai.speed){case 1:$("#kyodai_speed").css("color","#66CC00");break;case 3:$("#kyodai_speed").css("color","#3399FF");break;case 5:$("#kyodai_speed").css("color","#7907e0");break;case 7:$("#kyodai_speed").css("color","#FF9933");break;case 9:$("#kyodai_speed").css("color","#FF0000");kyodai.add(3)}$("#kyodai_speed").html("Speed x "+kyodai.speed+"<br/>+ "+kyodai.speedscore+" points");$("#kyodai_speed").fadeIn("slow");$("#kyodai_speed").fadeOut("slow")};
kyodai.updatecombo=function(){switch(kyodai.highestcombo){case 5:$("#kyodai_combo").css("color","#66CC00");$("#kyodai_board").css("color","#66CC00");break;case 10:$("#kyodai_combo").css("color","#3399FF");$("#kyodai_board").css("color","#3399FF");break;case 15:$("#kyodai_combo").css("color","#7907e0");$("#kyodai_board").css("color","#7907e0");kyodai.add(1);break;case 20:$("#kyodai_combo").css("color","#FF9933");$("#kyodai_board").css("color","#FF9933");kyodai.add(2);break;case 30:$("#kyodai_combo").css("color",
"#FF0000");$("#kyodai_board").css("color","#FF0000");kyodai.add(3)}$("#kyodai_combo").html("Combo: "+kyodai.combo+" / "+kyodai.highestcombo+" Hits")};kyodai.updatescore=function(){$("#kyodai_scores").html("Scores : "+kyodai.scores)};kyodai.updateupdate=function(a){$("#kyodai_update").html("+"+a+"!");$("#kyodai_update").fadeIn("normal");$("#kyodai_update").fadeOut("normal")};
kyodai.count=function(){clearInterval(kyodai.timeid);$("#kyodai_count img").attr("src",kyodai.getCachedImage("count1.png"));$("#kyodai_count img").width(328);kyodai.counts=328;kyodai.timeid=setInterval(function(){kyodai.counts-=1;$("#kyodai_count img").width(kyodai.counts);switch(kyodai.counts){case 295:$("#kyodai_count img").attr("src",kyodai.getCachedImage("count2.png"));break;case 210:$("#kyodai_count img").attr("src",kyodai.getCachedImage("count3.png"));break;case 100:$("#kyodai_count img").attr("src",
kyodai.getCachedImage("count4.png"));break;case 65:$("#kyodai_count img").attr("src",kyodai.getCachedImage("count5.png"));break;case 30:$("#kyodai_count img").attr("src",kyodai.getCachedImage("count6.png"))}kyodai.counts<2&&kyodai.over("gameover")},80)};kyodai.random=function(a){for(var b=[];a.length;)b=b.splice(0,Math.floor(Math.random()*(b.length+1))).concat(a.splice(Math.floor(Math.random()*a.length),1),b);return b};
kyodai.add=function(a){if(kyodai.pptnum[a])$("#kyodai_ppt_"+a+"_num").attr("src",kyodai.getCachedImage("tool_num_"+ ++kyodai.pptnum[a]+".png"));else{kyodai.pptnum[a]=1;$("#kyodai_ppt").append("<img id=kyodai_ppt_"+a+' src="'+kyodai.getCachedImage("tool"+a+".png")+'">');$("#kyodai_ppt_num").append("<img id=kyodai_ppt_"+a+'_num src="'+kyodai.getCachedImage("tool_num_1.png")+'" onclick="kyodai.use('+a+')">')}};
kyodai.use=function(a){kyodai.sound(4);kyodai.cancel();if(--kyodai.pptnum[a])$("#kyodai_ppt_"+a+"_num").attr("src",kyodai.getCachedImage("tool_num_"+kyodai.pptnum[a]+".png"));else{$("#kyodai_ppt_"+a).remove();$("#kyodai_ppt_"+a+"_num").remove()}switch(a){case 1:kyodai.cue(false);break;case 2:kyodai.reset();break;case 3:kyodai.cue(true)}};
kyodai.cue=function(a){for(var b=kyodai.shape,c=kyodai.pptnum[1],d=0;d<b.length;d++)if(c=kyodai.block[b[d].x+","+b[d].y])for(var e=d+1;e<b.length;e++)if(c==kyodai.block[b[e].x+","+b[e].y]){var f=b[d].x,j=b[d].y,k=b[e].x,l=b[e].y,m=kyodai.find(f,j,k,l);if(m){$("#kyodai_cuechoose").html('<img src = "'+kyodai.getCachedImage("choose.png")+'" style="position:absolute;left:'+f*35+"px;top:"+j*35+'px"><img src = "'+kyodai.getCachedImage("choose.png")+'" style="position:absolute;left:'+k*35+"px;top:"+l*35+
'px">');$("#kyodai_lines").html(m.join(""));$("#kyodai_lines img").fadeOut(1E3);$("#kyodai_cuechoose img").fadeOut(1E3);if(a){$("#kyodai_cuechoose").text("");kyodai.block[f+","+j]=0;kyodai.block[k+","+l]=0;kyodai.del(f,j,k,l)}return}}};kyodai.reset=function(){var a=[];for(var b in kyodai.block)a.push(kyodai.block[b]);kyodai.setting(a)};kyodai.sound=function(a){try{au_sound.GotoFrame(0);au_sound.GotoFrame(a);au_sound.Play()}catch(b){}};
kyodai.setTotalscores=function(a){kyodai.totalscores+=a;$("#myscore").html(kyodai.totalscores);kyodai.prefs.set("totalscores",kyodai.totalscores)};kyodai.setRecord=function(a){kyodai.record=a;$("#myrecord").html(a);kyodai.prefs.set("record",a)};kyodai.setLevel=function(a){kyodai.level=a;$("#levelimg").attr("src",kyodai.getCachedImage("level"+a+".png"));$("#mylevel").html("Level "+a);kyodai.prefs.set("level",a)};
kyodai.over=function(a){kyodai.cancel();clearInterval(kyodai.timeid);$("#kyodai_count img").width(0);$("#kyodai_items").html("");$("#kyodai_ppt_num").html("");$("#kyodai_remain").html("");$("#kyodai_scores").html("");$("#kyodai_combo").html("");$("#kyodai_hover").css("left","-2000px");$("#kyodai_choose").css("left","-2000px");$("#kyodai_ppt").html('<img src ="'+kyodai.getCachedImage("notool.png")+'">');document.onkeydown=null;if(a=="win"){a=kyodai.scores;for(var b=0,c=1;c<6;c++)if(kyodai.pptnum[c]>
0)b+=kyodai.pptnum[c];kyodai.scores+=kyodai.highestcombo*20+b*50;if(kyodai.scores>kyodai.record){kyodai.setRecord(kyodai.scores);$("#kyodai_center").html(kyodai.generateWin(a,kyodai.highestcombo,b,kyodai.scores,true))}else $("#kyodai_center").html(kyodai.generateWin(a,kyodai.highestcombo,b,kyodai.scores,false));$("#kyodai_center").css("background","url("+kyodai.getCachedImage("center_win.png")+") no-repeat");$("#kyodai_center").css("display","block");$("#centerbtn").click(function(){kyodai.start()});
kyodai.setTotalscores(kyodai.scores);kyodai.totalscores>kyodai.levelscore[kyodai.level+1]&&kyodai.levelup()}else{$("#kyodai_center").html(kyodai.generateOver());$("#kyodai_center").css("background","url("+kyodai.getCachedImage("center.png")+") no-repeat");$("#kyodai_center").css("display","block");$("#centerbtn").click(function(){kyodai.start()})}};
kyodai.generateWin=function(a,b,c,d,e){html='<div id="centertitle">You Win!</div>          <div id="centerboard" class="scorespan">            <span>Basic: <span class="green">'+a+'</span> x 1</span><br/>            <span>Combo: <span class="green">'+b+'</span> x 20</span><br/>            <span>Props: <span class="green">'+c+'</span> x 50</span><br/>            <hr size="1" noshade="noshade" style="color:#CCC;">            <span>Total scores: <span class="pink">'+d+'</span> points </span><br/>          </div>          <div id="centerbtn">New Game</div>';
if(e)html+='<div style="position:absolute;left:175px;top:55px;color:#53a9ff;">High<br/>Record<br/> '+kyodai.record+" !</div>";return html};kyodai.generateOver=function(){return html='<div id="centertitle" style="color:#FFF; margin-top:50px;">Game Over</div>          <div id="centerbtn" style="margin-top:30px;">New Game</div>'};kyodai.levelup=function(){kyodai.setLevel(kyodai.level+1)};
kyodai.cross=function(a,b){for(var c=a-1;c>-1;c--)if(kyodai.block[c+","+b])break;for(var d=a+1;d<kyodai.mapX;d++)if(kyodai.block[d+","+b])break;for(var e=b-1;e>-1;e--)if(kyodai.block[a+","+e])break;for(b=b+1;b<kyodai.mapY;b++)if(kyodai.block[a+","+b])break;return{x1:c,x2:d,y1:e,y2:b}};kyodai.passx=function(a,b,c){if(a<b)for(;++a<b;){if(kyodai.block[a+","+c])return false}else for(;++b<a;)if(kyodai.block[b+","+c])return false;return true};
kyodai.passy=function(a,b,c){if(a<b)for(;++a<b;){if(kyodai.block[c+","+a])return false}else for(;++b<a;)if(kyodai.block[c+","+b])return false;return true};kyodai.linex=function(a,b,c){var d=[];if(a<b)for(;a++<b;)d.push('<img src="'+kyodai.getCachedImage("linex.png")+'" style="position:absolute;left:'+(a*35-17)+"px;top:"+c*35+'px"/>');else for(;b++<a;)d.push('<img src="'+kyodai.getCachedImage("linex.png")+'"  style="position:absolute;left:'+(b*35-17)+"px;top:"+c*35+'px"/>');return d};
kyodai.liney=function(a,b,c){var d=[];if(a<b)for(;a++<b;)d.push('<img src="'+kyodai.getCachedImage("liney.png")+'" style="position:absolute;left:'+c*35+"px;top:"+(a*35-17)+'px"/>');else for(;b++<a;)d.push('<img src="'+kyodai.getCachedImage("liney.png")+'" style="position:absolute;left:'+c*35+"px;top:"+(b*35-17)+'px"/>');return d};
kyodai.find=function(a,b,c,d){var e=kyodai.cross(a,b);if(b==d&&e.x1<c&&c<e.x2)return kyodai.linex(a,c,b);if(a==c&&e.y1<d&&d<e.y2)return kyodai.liney(b,d,a);var f=kyodai.cross(c,d),j=e.x1<f.x1?f.x1:e.x1,k=e.x2>f.x2?f.x2:e.x2,l=e.y1<f.y1?f.y1:e.y1;e=e.y2>f.y2?f.y2:e.y2;if(j<a&&a<k&&l<d&&d<e)return kyodai.liney(b,d,a).concat(kyodai.linex(a,c,d));if(j<c&&c<k&&l<b&&b<e)return kyodai.liney(b,d,c).concat(kyodai.linex(a,c,b));if(a<c){f=a;var m=c,h=b,o=d}else{f=c;m=a;h=d;o=b}for(var g=f+1;g<m;g++)if(j<g&&
g<k&&kyodai.passy(h,o,g))return kyodai.liney(h,o,g).concat(kyodai.linex(f,g,h),kyodai.linex(g,m,o));if(b<d){g=b;var n=d,p=a,q=c}else{g=d;n=b;p=c;q=a}for(h=g+1;h<n;h++)if(l<h&&h<e&&kyodai.passx(p,q,h))return kyodai.linex(p,q,h).concat(kyodai.liney(g,h,p),kyodai.liney(h,n,q));for(q=p=o=h=true;h||o||p||q;){if(h)if(j<--f&&f<k){if(kyodai.passy(b,d,f))return kyodai.liney(b,d,f).concat(kyodai.linex(f,a,b),kyodai.linex(f,c,d))}else h=false;if(o)if(j<++m&&m<k){if(kyodai.passy(b,d,m))return kyodai.liney(b,
d,m).concat(kyodai.linex(m,a,b),kyodai.linex(m,c,d))}else o=false;if(p)if(l<--g&&g<e){if(kyodai.passx(a,c,g))return kyodai.linex(a,c,g).concat(kyodai.liney(g,b,a),kyodai.liney(g,d,c))}else p=false;if(q)if(l<++n&&n<e){if(kyodai.passx(a,c,n))return kyodai.linex(a,c,n).concat(kyodai.liney(n,b,a),kyodai.liney(n,d,c))}else q=false}return false};